services:
  uploadfile:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MINIO_ENDPOINT: "minio"
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - '3034:3001'
    depends_on:
      - minio
    networks:
      - minio-net

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge

volumes:
  minio_data:
    driver: local